version: "3.8"
services:
  frontend:
    build: ./dashboard
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST_URL=database
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=abcd1234
  database:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=abcd1234